### ISSUE TITLE
Enumerable Methods - Review

### ISSUE THREAD

**Issue by AbdumurodovaZulfizar** [DanSam5K/project-2-enumerable-methods#2]
Good job👍

**Comment by fortuneonyeka** [comment]
You are doing a nice job guys

**Comment by notlfish** [comment]
Nice job so far! 
You may want to have a look at the following links on [Enumerator](https://scoutapm.com/blog/ruby-enumerator),  the [docs on Enumerator](https://ruby-doc.org/core-2.6/Enumerator.html) and [this answer](https://stackoverflow.com/questions/8705389/how-to-decide-whether-an-optional-argument-was-given-or-not-in-a-ruby-method) on how to manage the problem of checking if a method with an optional argument did indeed get an argument passed to it.
